#!/bin/bash
# Generated by William Lam's VCF 9 Lab in a Box Script

echo enable.speed.of.physical.nics.validation=false >> /etc/vmware/vcf/domainmanager/application.properties
echo feature.vcf.internal.single.host.domain=true >> /home/vcf/feature.properties
chmod 755 /home/vcf/feature.properties
sed -i -e "/lcm.depot.adapter.port=.*/a lcm.depot.adapter.httpsEnabled=false" /opt/vmware/vcf/lcm/lcm-app/conf/application-prod.properties
echo 'y' | /opt/vmware/vcf/operationsmanager/scripts/cli/sddcmanager_restart_services.sh
